@startuml
left to right direction
skinparam rectangle {
  RoundCorner 8
}
actor "Quản trị viên" as Actor
rectangle "Cấu hình bot Discord" as Process
database "Cấu hình bot Discord" as Store
Actor --> Process : Bot token\nClient id\nClient secret\nQuyền bot
Process --> Store : Dữ liệu cần lưu/tra cứu
Store --> Process : Dữ liệu nghiệp vụ
Process --> Actor : Trạng thái cấu hình bot
@enduml
