@startuml
left to right direction
skinparam rectangle {
  RoundCorner 8
}
actor "Giáo viên" as Actor
rectangle "Tổng hợp báo cáo tài chính" as Process
database "Giao dịch, khoản học phí, học sinh, lớp học" as Store
Actor --> Process : Bộ lọc báo cáo
Process --> Store : Dữ liệu cần lưu/tra cứu
Store --> Process : Dữ liệu nghiệp vụ
Process --> Actor : Báo cáo tài chính\nSố dư học sinh
@enduml
