@startuml
left to right direction
skinparam rectangle {
  RoundCorner 8
}
actor "Học sinh, Discord" as Actor
rectangle "Uỷ quyền Discord học sinh" as Process
database "Học sinh, định danh Discord học sinh" as Store
Actor --> Process : Yêu cầu ủy quyền\nMã xác thực Discord
Process --> Store : Dữ liệu cần lưu/tra cứu
Store --> Process : Dữ liệu nghiệp vụ
Process --> Actor : Trạng thái ủy quyền\nQuyền thêm vào Guild lớp
@enduml
