@startuml
left to right direction
skinparam rectangle {
  RoundCorner 8
}
actor "Giáo viên" as Actor
rectangle "Quản lý buổi học" as Process
database "Lớp học, buổi học" as Store
Actor --> Process : Thông tin buổi học\nYêu cầu hủy buổi học
Process --> Store : Dữ liệu cần lưu/tra cứu
Store --> Process : Dữ liệu nghiệp vụ
Process --> Actor : Danh sách buổi học\nTrạng thái buổi học
@enduml
