@startuml
left to right direction
skinparam rectangle {
  RoundCorner 8
}
actor "Giáo viên, Quản trị viên" as Actor
rectangle "Xác thực đăng nhập" as Process
database "Tài khoản giáo viên" as Store
Actor --> Process : Tên đăng nhập\nMật khẩu
Process --> Store : Dữ liệu cần lưu/tra cứu
Store --> Process : Dữ liệu nghiệp vụ
Process --> Actor : Phiên đăng nhập\nThông tin người dùng\nThông báo lỗi
@enduml
